Repository DeveloperAcademy-POSTECH/MC2-morning-Team12-DreamLog, pull requests merged in 2023-05, with the labels that each got.

#2 [Setting] DreamLog#1 - 컨벤션 추가
  .DS_Store
  README.md
Labels: Setting

#14 [Setting] DreamLog#13 - readme 작성
  README.md
  mc2-DreamLog/mc2-DreamLog.xcodeproj/project.xcworkspace/xcuserdata/kimtaehyung.xcuserdatad/UserInterfaceState.xcuserstate
Labels: Setting

#27 [Fix] xcuserstate 병합 관련 gitignore
  .gitignore
  mc2-DreamLog/mc2-DreamLog.xcodeproj/project.xcworkspace/xcuserdata/kimtaehyung.xcuserdatad/UserInterfaceState.xcuserstate
Labels: Fix

#30 [Design]#23 CheerLog - 타이틀 추가
  mc2-DreamLog/mc2-DreamLog.xcodeproj/project.pbxproj
  mc2-DreamLog/mc2-DreamLog/View/CheerLogView.swift
  mc2-DreamLog/mc2-DreamLog/View/MainView.swift
Labels: Design

#34 [Feat]#29 DreamLog - 선 그리기 기능 추가
  mc2-DreamLog/mc2-DreamLog.xcodeproj/project.pbxproj
  mc2-DreamLog/mc2-DreamLog/View/Componets/EditDrawingMenuView.swift
  mc2-DreamLog/mc2-DreamLog/View/EditDrawingView.swift
Labels: Feat

#35 [Feat]#33 DreamLog - TutorialTextEditView 텍스트 추가 기능 구현
  mc2-DreamLog/mc2-DreamLog.xcodeproj/project.pbxproj
  mc2-DreamLog/mc2-DreamLog/View/Tutorial/TutorialTextEditView.swift
Labels: Feat

#44 [Add] DreamLog#34 - TutorialTextEditView 이미지 보드로 전달 구현
  mc2-DreamLog/mc2-DreamLog/View/Tutorial/TutorialTextEditView.swift
Labels: Add

#51 [Feat] #47 DreamLog - 그린 그림을 이미지로 변환
  mc2-DreamLog/mc2-DreamLog/View/EditDrawingView.swift
Labels: Feat

#54 Feature/#53 Color Preset 만들기
  mc2-DreamLog/mc2-DreamLog.xcodeproj/project.pbxproj
  mc2-DreamLog/mc2-DreamLog/Global/Extension/ColorExtension.swift
  mc2-DreamLog/mc2-DreamLog/Model/ColorPreset.swift
  mc2-DreamLog/mc2-DreamLog/View/Componets/EditColorView.swift
  mc2-DreamLog/mc2-DreamLog/View/EditDrawingView.swift
  mc2-DreamLog/mc2-DreamLog/View/Tutorial/TutorialTextEditView.swift
Labels: Chore

#55 [Refactor] DreamLog #52 - BoardElement 위치 position에서 offset으로 변경
  mc2-DreamLog/mc2-DreamLog/Model/TutorialBoardElement.swift
  mc2-DreamLog/mc2-DreamLog/View/Componets/EditMenuView.swift
  mc2-DreamLog/mc2-DreamLog/View/Componets/FixableImageView.swift
  mc2-DreamLog/mc2-DreamLog/View/EditDrawingView.swift
  mc2-DreamLog/mc2-DreamLog/View/Tutorial/TutorialTextEditView.swift
  mc2-DreamLog/mc2-DreamLog/View/Tutorial/TutorialView.swift
Labels: Refactor

#56 [Feat] DreamLog#50 - 이모지 Component 제작
  mc2-DreamLog/mc2-DreamLog.xcodeproj/project.pbxproj
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/sticker_break.imageset/Contents.json
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/sticker_break.imageset/bubble_break.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/sticker_check.imageset/Contents.json
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/sticker_check.imageset/sticker_check.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/sticker_desk.imageset/Contents.json
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/sticker_desk.imageset/sticker_desk.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/sticker_fire.imageset/Contents.json
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/sticker_fire.imageset/sticker_fire.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/sticker_flag.imageset/Contents.json
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/sticker_flag.imageset/sticker_flag.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/sticker_good.imageset/Contents.json
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/sticker_good.imageset/bubble_good.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/sticker_like.imageset/Contents.json
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/sticker_like.imageset/sticker_like.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/sticker_love.imageset/Contents.json
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/sticker_love.imageset/sticker_love.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/sticker_never.imageset/Contents.json
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/sticker_never.imageset/bubble_never.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/sticker_run.imageset/Contents.json
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/sticker_run.imageset/sticker_run.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/sticker_start.imageset/Contents.json
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/sticker_start.imageset/sticker_start.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/sticker_trophy.imageset/Contents.json
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/sticker_trophy.imageset/sticker_trophy.png
  mc2-DreamLog/mc2-DreamLog/View/Componets/EditMenuView.swift
  mc2-DreamLog/mc2-DreamLog/View/Componets/EmojiPicker.swift
Labels: Feat

#58 [Feat] DreamLog #57 - 공유버튼에 기능 할당
  mc2-DreamLog/mc2-DreamLog.xcodeproj/project.pbxproj
  mc2-DreamLog/mc2-DreamLog/View/Componets/ShareSheet.swift
  mc2-DreamLog/mc2-DreamLog/View/DreamBoardView.swift
Labels: Feat

#68 [Fix] DreamLog#64 - 메인보드 레이아웃 수정
  mc2-DreamLog/mc2-DreamLog.xcodeproj/project.pbxproj
  mc2-DreamLog/mc2-DreamLog/Global/Modifier/MenuButtonModifier.swift
  mc2-DreamLog/mc2-DreamLog/View/Componets/EditMenuView.swift
  mc2-DreamLog/mc2-DreamLog/View/Componets/EmojiPicker.swift
  mc2-DreamLog/mc2-DreamLog/View/Tutorial/TuturialBoardView.swift
Labels: Fix

#70 [Feat] DreamLog#69 - TutorialBoardView - WidgetSize 보여주는 기능 구현
  mc2-DreamLog/mc2-DreamLog.xcodeproj/project.pbxproj
  mc2-DreamLog/mc2-DreamLog/View/Componets/EditMenuView.swift
  mc2-DreamLog/mc2-DreamLog/View/Componets/WidgetAreaView.swift
  mc2-DreamLog/mc2-DreamLog/View/Componets/WidgetSizeButtonsView.swift
  mc2-DreamLog/mc2-DreamLog/View/Tutorial/TuturialBoardView.swift
Labels: Feat

#75 [Feat] DreamLog#71 - EditDrawingView에 그림 전체 삭제버튼, Undo 버튼, Redo 버튼 구현
  mc2-DreamLog/mc2-DreamLog/View/EditDrawingView.swift
Labels: Feat

#76 Feature/#74 폰트 파일 추가
  mc2-DreamLog/mc2-DreamLog.xcodeproj/project.pbxproj
  mc2-DreamLog/mc2-DreamLog/Global/Extension/FontExtension.swift
  mc2-DreamLog/mc2-DreamLog/Global/Resources/Font/GabiaHeuldot.otf
  mc2-DreamLog/mc2-DreamLog/Global/Resources/Font/JalnanOTF.otf
  mc2-DreamLog/mc2-DreamLog/Global/Resources/Font/Pilseung Gothic Regular.otf
  mc2-DreamLog/mc2-DreamLog/Global/Resources/Font/The Jamsil OTF 4 Medium.otf
  mc2-DreamLog/mc2-DreamLog/View/Tutorial/TutorialTextEditView.swift
  mc2-DreamLog/mc2-DreamLog/mc2_DreamLogApp.swift
Labels: Add

#83 [Feat] DreamLog#78 - EditDrawingView에 Redo / Undo / Reset 버튼 아이콘 추가 & 펜 타입 추가
  mc2-DreamLog/mc2-DreamLog/View/EditDrawingView.swift
Labels: Feat

#84 [Feat] DreamLog#80 - 드림보드 이미지 캡쳐 및 사이즈 조절
  mc2-DreamLog/mc2-DreamLog.xcodeproj/project.pbxproj
  mc2-DreamLog/mc2-DreamLog/Model/Tab1Model.swift
  mc2-DreamLog/mc2-DreamLog/View/DreamBoardView.swift
  mc2-DreamLog/mc2-DreamLog/View/MainView.swift
  mc2-DreamLog/mc2-DreamLog/View/Tutorial/TuturialBoardView.swift
Labels: Feat

#85 [Feat] Color Preset #82 - ColorExtension, ColorPreset에 색상 추가 (Black & White)
  mc2-DreamLog/mc2-DreamLog/Global/Extension/ColorExtension.swift
  mc2-DreamLog/mc2-DreamLog/Model/ColorPreset.swift
Labels: Feat, Chore

#88 [Fix] DreamLog#73 TutorialBoardView에서 이미지 focus되어있는 상태에서 EditMenu버튼들 …
  mc2-DreamLog/mc2-DreamLog/View/Componets/EditMenuView.swift
  mc2-DreamLog/mc2-DreamLog/View/Componets/EmojiPicker.swift
  mc2-DreamLog/mc2-DreamLog/View/Componets/FixableImageView.swift
  mc2-DreamLog/mc2-DreamLog/View/EditDrawingView.swift
  mc2-DreamLog/mc2-DreamLog/View/Tutorial/TutorialTextEditView.swift
  mc2-DreamLog/mc2-DreamLog/View/Tutorial/TuturialBoardView.swift
Labels: Fix

#89 [Feat] Tab1 View 레이아웃 수정 및 응원 문구 표시
  mc2-DreamLog/mc2-DreamLog/Global/Extension/ColorExtension.swift
  mc2-DreamLog/mc2-DreamLog/View/DreamBoardView.swift
  mc2-DreamLog/mc2-DreamLog/View/MainView.swift
Labels: Feat

#93 [Fix] DreamLog#72 - 편집뷰에서 사진, 이모지, 텍스트, 그림 불러올때 기본 위치 설정
  mc2-DreamLog/mc2-DreamLog.xcodeproj/project.pbxproj
  mc2-DreamLog/mc2-DreamLog/Model/TutorialBoardElement.swift
  mc2-DreamLog/mc2-DreamLog/View/Componets/EditMenuView.swift
  mc2-DreamLog/mc2-DreamLog/View/Componets/EmojiPicker.swift
  mc2-DreamLog/mc2-DreamLog/View/EditDrawingView.swift
  mc2-DreamLog/mc2-DreamLog/View/Tutorial/TutorialTextEditView.swift
  mc2-DreamLog/mc2-DreamLog/View/Tutorial/TutorialView.swift
Labels: Fix

#98 [Feat] DreamLog#97 - DreamBoardEditView 기능 구현
  mc2-DreamLog/mc2-DreamLog.xcodeproj/project.pbxproj
  mc2-DreamLog/mc2-DreamLog/View/DreamBoardEditView.swift
  mc2-DreamLog/mc2-DreamLog/View/DreamBoardView.swift
  mc2-DreamLog/mc2-DreamLog/mc2_DreamLogApp.swift
Labels: Feat

#100 [Feat] DreamLog/#99 - DreamBoardEditView 기능만 구현
  mc2-DreamLog/mc2-DreamLog.xcodeproj/project.pbxproj
  mc2-DreamLog/mc2-DreamLog.xcodeproj/xcshareddata/xcschemes/DreamBoardWidgetExtension.xcscheme
  mc2-DreamLog/mc2-DreamLog.xcodeproj/xcshareddata/xcschemes/mc2-DreamLog.xcscheme
  mc2-DreamLog/mc2-DreamLog/Model/DBHelper.swift
  mc2-DreamLog/mc2-DreamLog/Model/DreamLogModel.swift
  mc2-DreamLog/mc2-DreamLog/View/DreamBoardEditView.swift
  mc2-DreamLog/mc2-DreamLog/View/DreamBoardView.swift
  mc2-DreamLog/mc2-DreamLog/View/Tutorial/TuturialBoardView.swift
  mc2-DreamLog/mc2-DreamLog/mc2_DreamLogApp.swift
Labels: Feat

#106 [Fix] DreamLog #103 DreamBoardEdit 화면 전환 방식 수정하기
  mc2-DreamLog/mc2-DreamLog/View/DreamBoardEditView.swift
Labels: Fix

#105 Feature/#94 - 디데이 계산
  mc2-DreamLog/mc2-DreamLog.xcodeproj/project.pbxproj
  mc2-DreamLog/mc2-DreamLog.xcodeproj/xcuserdata/kimtaehyung.xcuserdatad/xcschemes/xcschememanagement.plist
  mc2-DreamLog/mc2-DreamLog/View/DDayCalendarView.swift
  mc2-DreamLog/mc2-DreamLog/View/DreamBoardView.swift
  mc2-DreamLog/mc2-DreamLog/View/Tutorial/TutorialCalendarView.swift
Labels: Feat

#111 [Fix] DreamLog #110 최적화 패치 -> 기존에 있던 이미지 삭제 후 새로운 이미지 추가
  mc2-DreamLog/mc2-DreamLog/Model/DBHelper.swift
  mc2-DreamLog/mc2-DreamLog/View/DreamBoardView.swift
  mc2-DreamLog/mc2-DreamLog/View/Tutorial/TutorialView.swift
Labels: Fix

#113 [Fix] DreamLog #112 DBHelper 싱글톤 패턴 적용
  mc2-DreamLog/mc2-DreamLog/Model/DBHelper.swift
  mc2-DreamLog/mc2-DreamLog/View/DreamBoardEditView.swift
  mc2-DreamLog/mc2-DreamLog/View/DreamBoardView.swift
  mc2-DreamLog/mc2-DreamLog/View/Tutorial/TuturialBoardView.swift
  mc2-DreamLog/mc2-DreamLog/mc2_DreamLogApp.swift
Labels: Fix

#115 Feature/#90 - Widget 디자인
  mc2-DreamLog/DreamBoardWidget/Assets.xcassets/BoardDummy.imageset/BoardDummy.jpeg
  mc2-DreamLog/DreamBoardWidget/Assets.xcassets/BoardDummy.imageset/Contents.json
  mc2-DreamLog/DreamBoardWidget/DreamBoardWidget.swift
Labels: Feat

#117 [Feat] DreamLog #114 - 두번째 탭 데이터 관련 처리
  mc2-DreamLog/mc2-DreamLog/Model/DBHelper.swift
  mc2-DreamLog/mc2-DreamLog/Model/DreamLogModel.swift
  mc2-DreamLog/mc2-DreamLog/View/DreamBoardEditView.swift
  mc2-DreamLog/mc2-DreamLog/View/DreamLogView.swift
  mc2-DreamLog/mc2-DreamLog/mc2_DreamLogApp.swift
Labels: Feat

#119 [Fix] #118 - 수정기능 보류, 수정기능 일단 빼두기 및 기타 작업
  mc2-DreamLog/mc2-DreamLog.xcodeproj/project.pbxproj
  mc2-DreamLog/mc2-DreamLog/ContentView.swift
  mc2-DreamLog/mc2-DreamLog/Model/BoardElement.swift
  mc2-DreamLog/mc2-DreamLog/Model/DBHelper.swift
  mc2-DreamLog/mc2-DreamLog/View/Componets/FixableImageView.swift
  mc2-DreamLog/mc2-DreamLog/View/DDayCalendarView.swift
  mc2-DreamLog/mc2-DreamLog/View/DreamBoardEditView.swift
  mc2-DreamLog/mc2-DreamLog/View/DreamBoardView.swift
  mc2-DreamLog/mc2-DreamLog/View/DreamLogView.swift
  mc2-DreamLog/mc2-DreamLog/View/MainView.swift
  mc2-DreamLog/mc2-DreamLog/View/Tutorial/TutorialCalendarView.swift
  mc2-DreamLog/mc2-DreamLog/View/Tutorial/TutorialTextEditView.swift
  mc2-DreamLog/mc2-DreamLog/View/Tutorial/TuturialBoardView.swift
  mc2-DreamLog/mc2-DreamLog/mc2_DreamLogApp.swift
Labels: Fix

#123 [Fix] DreamLog#122 - TutorialBoardView 진입 전 입력된 텍스트 폰트 적용
  mc2-DreamLog/mc2-DreamLog/View/Tutorial/TutorialView.swift
Labels: Fix

#126 [Fix] DreamLog#124 - TutorialStartView 디자인 수정
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/TutoStart1.imageset/Contents.json
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/TutoStart1.imageset/TutoStart1.jpg
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/TutoStart2.imageset/Contents.json
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/TutoStart2.imageset/TutoStart2.jpg
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/TutoStart3.imageset/Contents.json
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/TutoStart3.imageset/TutoStart3.jpg
  mc2-DreamLog/mc2-DreamLog/View/Tutorial/TutorialStartView.swift
Labels: Fix

#130 [Fix] DreamLog#127 - MainBoardView Dummy Image 추가 및 DreamLogView 버튼 디자인 수정
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/MainDummyImage.imageset/Contents.json
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/MainDummyImage.imageset/MainDummyImage.png
  mc2-DreamLog/mc2-DreamLog/Global/Extension/ColorExtension.swift
  mc2-DreamLog/mc2-DreamLog/View/DreamBoardView.swift
  mc2-DreamLog/mc2-DreamLog/View/DreamLogView.swift
Labels: Fix

#131 [Feat] DreamLog/#129 TutorialBoardView, DreamBoardEditView에서 다음화면으로 넘…
  mc2-DreamLog/mc2-DreamLog.xcodeproj/project.pbxproj
  mc2-DreamLog/mc2-DreamLog/View/DreamBoardEditView.swift
  mc2-DreamLog/mc2-DreamLog/View/LoadingView.swift
  mc2-DreamLog/mc2-DreamLog/View/Tutorial/TuturialBoardView.swift
Labels: Feat

#134 [Chore] DreamLog #133 응원 확인 버튼시 알림창 텍스트 필드 초기화
  mc2-DreamLog/mc2-DreamLog/View/DreamBoardView.swift
Labels: Chore

#136 [Design] DreamLog #135 - CheerLogView 탭 디자인 다른 뷰와 통일
  mc2-DreamLog/mc2-DreamLog/View/CheerLogView.swift
Labels: Design

#137 [Feat] DreamLog#132 - TutorialBoardElement - BoradElement 초기 위치 변수를 T…
  mc2-DreamLog/mc2-DreamLog/Model/TutorialBoardElement.swift
  mc2-DreamLog/mc2-DreamLog/View/Componets/EditMenuView.swift
  mc2-DreamLog/mc2-DreamLog/View/Componets/EmojiPicker.swift
  mc2-DreamLog/mc2-DreamLog/View/EditDrawingView.swift
  mc2-DreamLog/mc2-DreamLog/View/Tutorial/TutorialStartView.swift
  mc2-DreamLog/mc2-DreamLog/View/Tutorial/TutorialTextEditView.swift
  mc2-DreamLog/mc2-DreamLog/View/Tutorial/TutorialView.swift
Labels: Fix

#138 [Feat] DreamLog #128 - 위젯 & Sqlite 데이터 연동, 위젯 기능 구현
  mc2-DreamLog/DreamBoardWidget/Assets.xcassets/WidgetDummyImage.imageset/Contents.json
  mc2-DreamLog/DreamBoardWidget/Assets.xcassets/WidgetDummyImage.imageset/WidgetDummyImage.png
  mc2-DreamLog/DreamBoardWidget/DreamBoardWidget.swift
  mc2-DreamLog/DreamBoardWidgetExtension.entitlements
  mc2-DreamLog/mc2-DreamLog.xcodeproj/project.pbxproj
  mc2-DreamLog/mc2-DreamLog/Global/Extension/DBHelperExtension.swift
  mc2-DreamLog/mc2-DreamLog/Global/Extension/FileManagerExtension.swift
  mc2-DreamLog/mc2-DreamLog/Model/DBHelper.swift
  mc2-DreamLog/mc2-DreamLog/Model/ImageFileManager.swift
  mc2-DreamLog/mc2-DreamLog/View/CheerLogView.swift
  mc2-DreamLog/mc2-DreamLog/View/DreamBoardEditView.swift
  mc2-DreamLog/mc2-DreamLog/View/DreamBoardView.swift
  mc2-DreamLog/mc2-DreamLog/View/DreamLogView.swift
  mc2-DreamLog/mc2-DreamLog/View/Tutorial/TuturialBoardView.swift
  mc2-DreamLog/mc2-DreamLog/mc2-DreamLog.entitlements
  mc2-DreamLog/mc2-DreamLog/mc2_DreamLogApp.swift
Labels: Feat

#141 [Setting] DreamLog #140 App icon 추가
  mc2-DreamLog/mc2-DreamLog.xcodeproj/project.pbxproj
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/100.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/102.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/1024.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/114.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/120.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/128.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/144.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/152.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/16.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/167.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/172.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/180.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/196.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/20.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/216.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/256.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/29.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/32.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/40.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/48.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/50.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/512.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/55.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/57.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/58.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/60.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/64.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/66.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/72.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/76.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/80.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/87.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/88.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/92.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: Setting

#143 [Add]DreamLog # 142 - 위젯 기본 이미지 크기 완료
  mc2-DreamLog/DreamBoardWidget/DreamBoardWidget.swift
  mc2-DreamLog/mc2-DreamLog.xcodeproj/project.pbxproj
Labels: Add

#144 [Fix] DreamLog#139 - 보드 저장시 위젯 사이즈 캡쳐 오류 수정
  mc2-DreamLog/mc2-DreamLog/View/DreamBoardEditView.swift
  mc2-DreamLog/mc2-DreamLog/View/Tutorial/TuturialBoardView.swift
Labels: Fix

#146 [Fix] DreamLog#145 - 위젯 더미 이미지 변경
  mc2-DreamLog/DreamBoardWidget/Assets.xcassets/WidgetDuimmyImageRectangle.imageset/Contents.json
  mc2-DreamLog/DreamBoardWidget/Assets.xcassets/WidgetDuimmyImageRectangle.imageset/WidgetDuimmyImageRectangle.jpg
  mc2-DreamLog/DreamBoardWidget/Assets.xcassets/WidgetDuimmyImageSquare.imageset/Contents.json
  mc2-DreamLog/DreamBoardWidget/Assets.xcassets/WidgetDuimmyImageSquare.imageset/WidgetDuimmyImageSquare.jpg
  mc2-DreamLog/DreamBoardWidget/Assets.xcassets/하지만.imageset/Contents.json
  mc2-DreamLog/DreamBoardWidget/Assets.xcassets/하지만.imageset/WidgetDuimmyImageSquare.jpg
  mc2-DreamLog/DreamBoardWidget/DreamBoardWidget.swift
Labels: Fix

#148 [Fix] DreamLog#147 - Tab1, Tab2 상단 디자인 수정
  mc2-DreamLog/mc2-DreamLog/View/CheerLogView.swift
  mc2-DreamLog/mc2-DreamLog/View/DreamLogView.swift
Labels: Fix

#150 [Fix] EditDrawingView - 붓 두께 기본값 조절, 버튼 하단 짤림 수정
  mc2-DreamLog/mc2-DreamLog/View/EditDrawingView.swift
Labels: Fix

#153 [Fix] DreamLog#152 - TutorialTextEditView 텍스트 이미지 해상도 높이기
  mc2-DreamLog/mc2-DreamLog.xcodeproj/project.pbxproj
  mc2-DreamLog/mc2-DreamLog/View/Tutorial/TutorialTextEditView.swift
Labels: Fix

#157 [Fix] DreamLog#151 - Process indicator 디자인 수정(LoadingView)
  mc2-DreamLog/mc2-DreamLog/View/LoadingView.swift
Labels: Fix

#158 [Add] DreamLog#155 - 회전 버튼 크기 및 색상 조정
  mc2-DreamLog/mc2-DreamLog/View/Componets/FixableImageView.swift
Labels: Add

#159 [Fix]DreamLog#154 - 글자 클릭 시에도 alert창 뜨게하기
  mc2-DreamLog/mc2-DreamLog/View/DreamBoardView.swift
Labels: Fix

#160 [Add] DreamLog#156 - 키보드 올라온 뒤에 화면 터치 시 키보드 다시 내리기
  mc2-DreamLog/mc2-DreamLog.xcodeproj/project.pbxproj
  mc2-DreamLog/mc2-DreamLog/Global/Extension/UIApplication.swift
  mc2-DreamLog/mc2-DreamLog/View/Tutorial/TutorialView.swift
Labels: Add

#162 [Feat]DreamLog#161 - 튜토리얼 위젯뷰 추가
  mc2-DreamLog/mc2-DreamLog/View/Tutorial/TutorialCalendarView.swift
Labels: Feat

#164 [Fix] DreamLog#163 - AppIcon 변경
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/100.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/102.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/1024.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/114.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/120.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/128.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/144.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/152.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/16.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/167.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/172.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/180.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/196.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/20.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/216.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/256.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/29.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/32.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/40.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/48.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/50.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/512.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/55.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/57.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/58.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/60.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/64.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/66.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/72.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/76.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/80.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/87.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/88.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/AppIcon.appiconset/92.png
Labels: Fix

#167 [Feat] DreamLog#166 - EditMenuView - 드림보드 수정시 전체 삭제버튼 구현
  mc2-DreamLog/mc2-DreamLog.xcodeproj/project.pbxproj
  mc2-DreamLog/mc2-DreamLog/View/Componets/EditMenuView.swift
Labels: Feat

#169 Feature/#165 LanchScreen 로고 깨짐 오류 수정 및 TutorialStart 페이지 버튼 위치 수정
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/LanchScreen.imageset/Contents.json
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/LanchScreen.imageset/LanchScreen.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/하지만 1.imageset/Contents.json
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/하지만 1.imageset/LanchScreen.png
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/하지만.imageset/Contents.json
  mc2-DreamLog/mc2-DreamLog/Assets.xcassets/하지만.imageset/LanchScreen.png
  mc2-DreamLog/mc2-DreamLog/Info.plist
  mc2-DreamLog/mc2-DreamLog/View/Tutorial/TutorialStartView.swift
Labels: Fix

#174 [Fix] DreamLog#171 - Tab1 아이콘 수정 및 응원 문구 위치 수정
  mc2-DreamLog/mc2-DreamLog/View/DreamBoardView.swift
Labels: Fix

#177 [Chore] DreamLog #176 튜토리얼에서 데이터 안 넘어가는 것 개선??
  mc2-DreamLog/DreamBoardWidget/DreamBoardWidget.swift
  mc2-DreamLog/mc2-DreamLog/Global/Extension/DBHelperExtension.swift
  mc2-DreamLog/mc2-DreamLog/Model/ImageFileManager.swift
  mc2-DreamLog/mc2-DreamLog/View/DDayCalendarView.swift
  mc2-DreamLog/mc2-DreamLog/View/Tutorial/TuturialBoardView.swift
Labels: Chore

#179 [Fix] DreamLog #178 캘린더 subtitle변경, 디테일뷰 사진 리사이즈, 앱 이름 표시 변경
  mc2-DreamLog/mc2-DreamLog.xcodeproj/project.pbxproj
  mc2-DreamLog/mc2-DreamLog/View/DreamLogView.swift
  mc2-DreamLog/mc2-DreamLog/View/Tutorial/TutorialCalendarView.swift
Labels: Fix

#181 [Feat] DreamLog #180 TutorialBoard <-> Calendar 왔다갔다해도 로그 데이터는 하나만 저장
  mc2-DreamLog/mc2-DreamLog/Global/Extension/DBHelperExtension.swift
  mc2-DreamLog/mc2-DreamLog/Global/Protocol/DreamLogTableProtocol.swift
  mc2-DreamLog/mc2-DreamLog/View/Tutorial/TuturialBoardView.swift
Labels: Feat

#189 [Fix] DreamLog #188 다크모드 미실행 설정, 전체삭제버튼 alert 추가
  mc2-DreamLog/mc2-DreamLog.xcodeproj/project.pbxproj
  mc2-DreamLog/mc2-DreamLog/Info.plist
  mc2-DreamLog/mc2-DreamLog/View/Componets/EditMenuView.swift
Labels: Fix

#191 [Fix] 이미지 교체, 위젯 다크모드 -> 라이트모드
  mc2-DreamLog/DreamBoardWidget/Assets.xcassets/BoardDummy.imageset/BoardDummy.jpeg
  mc2-DreamLog/DreamBoardWidget/Assets.xcassets/BoardDummy.imageset/Contents.json
  mc2-DreamLog/DreamBoardWidget/Assets.xcassets/하지만.imageset/Contents.json
  mc2-DreamLog/DreamBoardWidget/Assets.xcassets/하지만.imageset/WidgetDuimmyImageSquare.jpg
  mc2-DreamLog/DreamBoardWidget/DreamBoardWidget.swift
  mc2-DreamLog/DreamBoardWidget/Info.plist
  mc2-DreamLog/mc2-DreamLog.xcodeproj/project.pbxproj
  mc2-DreamLog/mc2-DreamLog/Global/Resources/Assets.xcassets/BoardDummy.imageset/BoardDummy.jpeg
  mc2-DreamLog/mc2-DreamLog/Global/Resources/Assets.xcassets/BoardDummy.imageset/Contents.json
  mc2-DreamLog/mc2-DreamLog/Global/Resources/Assets.xcassets/TutoSheet1.imageset/TutoSheet1.png
  mc2-DreamLog/mc2-DreamLog/Global/Resources/Assets.xcassets/TutoSheet1.imageset/TutoSheet1@2x.png
  mc2-DreamLog/mc2-DreamLog/Global/Resources/Assets.xcassets/TutoSheet1.imageset/TutoSheet1@3x.png
  mc2-DreamLog/mc2-DreamLog/Global/Resources/Assets.xcassets/TutoSheet2.imageset/TutoSheet2.png
  mc2-DreamLog/mc2-DreamLog/Global/Resources/Assets.xcassets/TutoSheet2.imageset/TutoSheet2@2x.png
  mc2-DreamLog/mc2-DreamLog/Global/Resources/Assets.xcassets/TutoSheet2.imageset/TutoSheet2@3x.png
  mc2-DreamLog/mc2-DreamLog/Global/Resources/Assets.xcassets/TutoStart1.imageset/Contents.json
  mc2-DreamLog/mc2-DreamLog/Global/Resources/Assets.xcassets/TutoStart1.imageset/TutoStart1.png
  mc2-DreamLog/mc2-DreamLog/Global/Resources/Assets.xcassets/TutoStart1.imageset/TutoStart1@2x.png
  mc2-DreamLog/mc2-DreamLog/Global/Resources/Assets.xcassets/TutoStart1.imageset/TutoStart1@3x.png
  mc2-DreamLog/mc2-DreamLog/Global/Resources/Assets.xcassets/TutoStart2.imageset/Contents.json
  mc2-DreamLog/mc2-DreamLog/Global/Resources/Assets.xcassets/TutoStart2.imageset/TutoStart2@2x.png
  mc2-DreamLog/mc2-DreamLog/Global/Resources/Assets.xcassets/TutoStart2.imageset/TutoStart2@3x.png
  mc2-DreamLog/mc2-DreamLog/Global/Resources/Assets.xcassets/TutoStart3.imageset/Contents.json
  mc2-DreamLog/mc2-DreamLog/Global/Resources/Assets.xcassets/TutoStart3.imageset/TutoStart3.png
  mc2-DreamLog/mc2-DreamLog/Global/Resources/Assets.xcassets/TutoStart3.imageset/TutoStart3@2x.png
  mc2-DreamLog/mc2-DreamLog/Global/Resources/Assets.xcassets/TutoStart3.imageset/TutoStart3@3x.png
  mc2-DreamLog/mc2-DreamLog/Global/Resources/Assets.xcassets/widgetMainscreen.imageset/Contents.json
  mc2-DreamLog/mc2-DreamLog/Global/Resources/Assets.xcassets/widgetMainscreen.imageset/widgetMainscreen .png
  mc2-DreamLog/mc2-DreamLog/Global/Resources/Assets.xcassets/widgetMainscreen.imageset/widgetMainscreen @2x.png
  mc2-DreamLog/mc2-DreamLog/Global/Resources/Assets.xcassets/widgetMainscreen.imageset/widgetMainscreen @3x.png
  mc2-DreamLog/mc2-DreamLog/Global/Resources/Assets.xcassets/widgetMainscreen.imageset/widgetMainscreen.png
  mc2-DreamLog/mc2-DreamLog/mc2_DreamLogApp.swift
Labels: Fix
